from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, TextIO


@dataclass
class SimlibHeader:
    """Header information for a SIMLIB file."""

    SURVEY: str = "LSST_TWILIGHT"
    FILTERS: str = "ugrizY"
    PIXSIZE: float = 0.200
    NPE_PIXEL_SATURATE: int = 90000
    PHOTFLAG_SATURATE: int = 2048
    PSF_UNIT: str = "NEA_PIXEL"


class SimlibWriter:
    """Minimal SNANA SIMLIB writer."""

    def __init__(self, fp: TextIO, header: SimlibHeader):
        """Create a writer.

        Parameters
        ----------
        fp : TextIO
            Open file-like object for writing.
        header : SimlibHeader
            Header configuration.
        """

        self.fp = fp
        self.header = header
        self._idx = 0
        self._current_libid: Optional[int] = None

    def write_header(self) -> None:
        """Write the SIMLIB header block."""

        h = self.header
        w = self.fp.write
        w("BEGIN LIBGEN\n\n")
        w("# Generated by twilight_planner\n")
        w(f"SURVEY:   {h.SURVEY}\n")
        w(f"FILTERS:  {h.FILTERS}\n")
        w(f"PIXSIZE:  {h.PIXSIZE:.3f}\n")
        w(f"NPE_PIXEL_SATURATE: {h.NPE_PIXEL_SATURATE}\n")
        w(f"PHOTFLAG_SATURATE:  {h.PHOTFLAG_SATURATE}\n")
        w(f"PSF_UNIT:  {h.PSF_UNIT}\n")
        w("\n")

    def start_libid(
        self,
        libid: int,
        ra_deg: float,
        dec_deg: float,
        nobs: int,
        comment: str = "",
    ) -> None:
        """Begin a new LIBID block for a target."""

        self._idx = 0
        self._current_libid = libid
        w = self.fp.write
        w("#--------------------------------------------\n")
        w(f"LIBID: {libid}\n")
        w(f"NOBS: {nobs}  RA: {ra_deg:11.6f}  DEC: {dec_deg:11.6f}\n")
        if comment:
            w(f"# {comment}\n")
        w("\n")
        w("#     MJD        ID   FLT GAIN NOISE SKYSIG NEA ZPTAVG ZPTERR MAG\n")

    def add_epoch(
        self,
        mjd: float,
        band: str,
        gain: float,
        rdnoise: float,
        skysig: float,
        nea: float,
        zpavg: float,
        zperr: float,
        mag: float = -99.0,
    ) -> None:
        """Write an `S:` row describing one exposure."""

        self._idx += 1
        self.fp.write(
            f"S: {mjd:11.4f}  {self._idx:3d}  {band:1s}  {gain:5.2f}  {rdnoise:5.2f}  {skysig:7.2f}  {nea:7.2f}  {zpavg:6.3f}  {zperr:5.3f}  {mag:>6}\n"
        )

    def end_libid(self) -> None:
        """Terminate current LIBID block."""

        if self._current_libid is not None:
            self.fp.write(f"END_LIBID: {self._current_libid}\n")
            self._current_libid = None

    def close(self) -> None:
        """Close the underlying file handle."""

        self.fp.close()
